;; (pcall require :user.setup.autopairs)
;; (pcall require :user.setup.catppuccin)
;; (pcall require :user.setup.copilot)
;; (pcall require :user.setup.dap)
;; (pcall require :user.setup.hop)
;; (pcall require :user.setup.matchparen)
;; (pcall require :user.setup.minimap)
;; (pcall require :user.setup.neoscroll)
;; (pcall require :user.setup.numb)
;; (pcall require :user.setup.telescope)
;; (pcall require :user.setup.treesitter)
;; (pcall require :user.setup.ufo)

